#!/bin/bash

set -e -o pipefail

output="$(acpi --battery 2>&1)"
# The ACPI /sys interface may return data even if there is no battery, so query using --proc as well
unsupported_output="No support for device type"
if [[ $? -ne 0 || "${output}" == "${unsupported_output}"* || "$(acpi --battery --proc 2>&1)" == "${unsupported_output}"* ]]; then
	exit 1
fi

if [[ "${output}" = *Discharging* ]]; then
    icon="${ICON_BATTERY_DISCHARGING}"
else
    icon="${ICON_BATTERY_PLUGGED_IN}"
fi

printf '%s%0.0f%%\n' "${icon}" "$(echo "${output}"|awk -F, '{s+=$2}END{print "",s/NR}')"
