#!/bin/bash

set -e -o pipefail

output="$(acpi --battery|grep -v unavailable 2>&1)"
exit_code=$?

if [[ $? -ne 0 ]]; then
	exit ${exit_code}
fi

if [[ "${output}" == "No support for device type"* ]]; then
    exit 1
fi

# Average of battery percentages, rounded to nearest integer
percentage="$(echo -n "${output}"|awk -F, '{s+=$2}END{print int(s/NR + 0.5)}')"
icon="${ICON_BATTERY_PLUGGED_IN}"

if [[ "${output}" = *Discharging* ]]; then
    icon="${ICON_BATTERY_DISCHARGING}"
    if [[ "${percentage}" -lt 13 && -n "${ICON_BATTERY_DISCHARGING_0}" ]]; then
        icon="${ICON_BATTERY_DISCHARGING_0}"
    elif [[ "${percentage}" -lt 38 && -n "${ICON_BATTERY_DISCHARGING_25}" ]]; then
        icon="${ICON_BATTERY_DISCHARGING_25}"
    elif [[ "${percentage}" -lt 63 && -n "${ICON_BATTERY_DISCHARGING_50}" ]]; then
        icon="${ICON_BATTERY_DISCHARGING_50}"
    elif [[ "${percentage}" -lt 88 && -n "${ICON_BATTERY_DISCHARGING_75}" ]]; then
        icon="${ICON_BATTERY_DISCHARGING_75}"
    elif [[ -n "${ICON_BATTERY_DISCHARGING_100}" ]]; then
        icon="${ICON_BATTERY_DISCHARGING_100}"
    fi
fi

printf '%s%0.0f%%\n' "${icon}" "${percentage}"
