#!/bin/bash

set -e -o pipefail

interface=$(iw dev|awk '{if ($1 == "Interface") { print $2 }}')

if ! type nmcli >/dev/null 2>&1 || [[ -z "${interface}" ]]; then
    exit 1
fi

output="$(nmcli d w|awk '{if ($1 == "*" && $2 != "SSID") {print $7}}')"
exit_code=$?

if [[ ${exit_code} -ne 0 ]]; then
    exit ${exit_code}
fi

if [[ -z "${output}" ]]; then
    quality='---'
else
    quality="${output}%"
fi

printf '%s\n' "${quality}"
